In [40]:
import pandas as pd
import numpy as np

In [ ]:
print("PANDAS")

PANDAS

In [42]:
'''
Series:It is an one dimensional array like object that can hold any data type, it is similar to column in a table   
'''

data=[3,4,5,6,7,89]
series=pd.Series(data)
print(series)
print(type(series))

0     3
1     4
2     5
3     6
4     7
5    89
dtype: int64
<class 'pandas.core.series.Series'>

In [43]:
#CREATE a series from dictionary
data2={'a':1,'b':2,'c':3}
series_pd=pd.Series(data2)
print(series_pd)

a    1
b    2
c    3
dtype: int64

In [44]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data=data,index=index)

a    10
b    20
c    30
dtype: int64

In [45]:
#dataframe : it is a table with column name ,column data storing in it 
data4={
    'name':['krishn','soham','jack'],
    'age':[25,20,30],
    'city':['pune','banglore','newyork'],
     

}

df=pd.DataFrame(data4)
print(type(df))
print("------------------------------------------------------------")
print(df)

<class 'pandas.core.frame.DataFrame'>
------------------------------------------------------------
     name  age      city
0  krishn   25      pune
1   soham   20  banglore
2    jack   30   newyork

In [46]:
#create a dataframe from a list of dictionaries
data5=[
    {'name':'soham','food':'banana'},
    {'name':'shweta','food':'apple'},
    {'name':'messi','food':'grapes'}
]

df1=pd.DataFrame(data5)
df1

     name    food
0   soham  banana
1  shweta   apple
2   messi  grapes

In [47]:
df2=pd.read_csv("sales.csv")
df2.head()

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,5/28/2010,669165933,6/27/2010,9925,255.28,159.42,2533654.00,1582243.50,951410.50
1,Central America and the Caribbean,Grenada,Cereal,Online,C,8/22/2012,963881480,9/15/2012,2804,205.70,117.11,576782.80,328376.44,248406.36
2,Europe,Russia,Office Supplies,Offline,L,5/2/2014,341417157,5/8/2014,1779,651.21,524.96,1158502.59,933903.84,224598.75
3,Sub-Saharan Africa,Sao Tome and Principe,Fruits,Online,C,6/20/2014,514321792,7/5/2014,8102,9.33,6.92,75591.66,56065.84,19525.82
4,Sub-Saharan Africa,Rwanda,Office Supplies,Offline,L,2/1/2013,115456712,2/6/2013,5062,651.21,524.96,3296425.02,2657347.52,639077.50

In [48]:
df2.tail()

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
95,Sub-Saharan Africa,Mali,Clothes,Online,M,7/26/2011,512878119,9/3/2011,888,109.28,35.84,97040.64,31825.92,65214.72
96,Asia,Malaysia,Fruits,Offline,L,11/11/2011,810711038,12/28/2011,6267,9.33,6.92,58471.11,43367.64,15103.47
97,Sub-Saharan Africa,Sierra Leone,Vegetables,Offline,C,6/1/2016,728815257,6/29/2016,1485,154.06,90.93,228779.10,135031.05,93748.05
98,North America,Mexico,Personal Care,Offline,M,7/30/2015,559427106,8/8/2015,5767,81.73,56.67,471336.91,326815.89,144521.02
99,Sub-Saharan Africa,Mozambique,Household,Offline,L,2/10/2012,665095412,2/15/2012,5367,668.27,502.54,3586605.09,2697132.18,889472.91

In [49]:
#ACCESSING DATA FROM DATAFRAME
df

     name  age      city
0  krishn   25      pune
1   soham   20  banglore
2    jack   30   newyork

In [50]:
print(df.loc[:])

     name  age      city
0  krishn   25      pune
1   soham   20  banglore
2    jack   30   newyork

In [70]:
print(df.iloc[0][0])## accessing element using normal indexing of matrices 
print(df.iloc[0][1])

krishn
25

C:\Users\Soham Khade\AppData\Local\Temp\ipykernel_15776\1122777451.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df.iloc[0][0])## accessing element using normal indexing of matrices
C:\Users\Soham Khade\AppData\Local\Temp\ipykernel_15776\1122777451.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df.iloc[0][1])

In [71]:
df1['salary']=[10000,20000,30000]

In [72]:

df1.at[1,'food']## accessing element using row index and column name

'apple'

In [73]:



df1

     name    food  age  salary
0   soham  banana   21   10000
1  shweta   apple   20   20000
2   messi  grapes   34   30000

In [74]:
df1.iat[0,1] ##accessing element using index

'banana'

In [75]:
#remove a column
'''
axis=1 that means you are dealing with column,
inplace =true means permanently delete the column
'''
df1.drop('salary',axis=1,inplace=True)

In [76]:
df1['age']=[21,20,34]

In [77]:
df1

     name    food  age
0   soham  banana   21
1  shweta   apple   20
2   messi  grapes   34

In [78]:
df1['age']=df1['age']+1

In [79]:
df1

     name    food  age
0   soham  banana   22
1  shweta   apple   21
2   messi  grapes   35

In [80]:
df1.describe()

            age
count   3.00000
mean   26.00000
std     7.81025
min    21.00000
25%    21.50000
50%    22.00000
75%    28.50000
max    35.00000

In [81]:
df1.dtypes

name    object
food    object
age      int64
dtype: object