In [1]:
print("data anyalsis with python")

data anyalsis with python

READING DATA FROM JSON USING PANDAS

In [5]:
import pandas as pd
from io import StringIO

data = '''
{
    "employee_name":"James",
    "email":"james@gmail.com",
    "job_profile":[
        {
            "title1":"Team lead",
            "title2":"Sr.Developer"
        }
    ]
}
'''

df = pd.read_json(StringIO(data))

print(df)

  employee_name            email  \
0         James  james@gmail.com

                                         job_profile
0  {'title1': 'Team lead', 'title2': 'Sr.Developer'}

In [7]:
df

,employee_name,email,job_profile
0,James,james@gmail.com,"{'title1': 'Team lead', 'title2': 'Sr.Developer'}"

In [8]:
df.to_json()

'{"employee_name":{"0":"James"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title1":"Team lead","title2":"Sr.Developer"}}}'

HERE ORIENT IS MEANS Which direction should Pandas arrange the data in JSON?"

In [9]:
df.to_json(orient="index")

'{"0":{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team lead","title2":"Sr.Developer"}}}'

In [10]:
df.to_json(orient="records")

'[{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team lead","title2":"Sr.Developer"}}]'

READING TABLES FROM WEBSITE USING PANDAS

In [12]:
!pip install lxml

Collecting lxml
  Downloading lxml-6.1.1-cp310-cp310-win_amd64.whl.metadata (3.6 kB)
Downloading lxml-6.1.1-cp310-cp310-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/4.0 MB 1.4 MB/s eta 0:00:03
   ------- -------------------------------- 0.8/4.0 MB 1.4 MB/s eta 0:00:03
   ---------- ----------------------------- 1.0/4.0 MB 1.4 MB/s eta 0:00:03
   ------------- -------------------------- 1.3/4.0 MB 1.4 MB/s eta 0:00:02
   --------------- ------------------------ 1.6/4.0 MB 1.4 MB/s eta 0:00:02
   ------------------ --------------------- 1.8/4.0 MB 1.4 MB/s eta 0:00:02
   -------------------- ------------------- 2.1/4.0 MB 1.4 MB/s eta 0:00:02
   -------------------------- ------------- 2.6/4.0 MB 1.4 MB/s eta 0:00:02
   ---------------------------- ----------- 2.9/4.0 MB 1.4 MB/s eta 0:00:01
   ------------------------------- -------- 3.1/4.0 MB 1.4 MB/s eta 0:00:01
   --------------------------------- ------ 3.4/4.0 MB 1.4 MB/s eta 0:00:01
   ------------------------------------ --- 3.7/4.0 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 1.4 MB/s  0:00:03
Installing collected packages: lxml
Successfully installed lxml-6.1.1

In [13]:
url="https://www.fdic.gov/bank-failures/failed-bank-list"
df=pd.read_html(url)

In [14]:
df

[                                            Bank Name                City  \
 0             Community Bank and Trust - West Georgia            LaGrange
 1                   Metropolitan Capital Bank & Trust             Chicago
 2                        The Santa Anna National Bank          Santa Anna
 3                                Pulaski Savings Bank             Chicago
 4                  The First National Bank of Lindsay             Lindsay
 5               Republic First Bank dba Republic Bank        Philadelphia
 6                                       Citizens Bank            Sac City
 7                            Heartland Tri-State Bank             Elkhart
 8                                 First Republic Bank       San Francisco
 9                                      Signature Bank            New York
 10                                Silicon Valley Bank         Santa Clara
 11                                  Almena State Bank              Almena
 12                         First City Bank of Florida   Fort Walton Beach
 13                               The First State Bank       Barboursville
 14                                 Ericson State Bank             Ericson
 15                   City National Bank of New Jersey              Newark
 16                                      Resolute Bank              Maumee
 17                              Louisa Community Bank              Louisa
 18                               The Enloe State Bank              Cooper
 19                Washington Federal Bank for Savings             Chicago
 20    The Farmers and Merchants State Bank of Argonia             Argonia
 21                                Fayette County Bank          Saint Elmo
 22  Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee
 23                                     First NBC Bank         New Orleans
 24                                      Proficio Bank  Cottonwood Heights

             State   Cert                Acquiring Institution  \
 0         Georgia  25796                          Anchor Bank
 1        Illinois  57488              First Independence Bank
 2           Texas   5520            Coleman County State Bank
 3        Illinois  28611                      Millennium Bank
 4        Oklahoma   4134               First Bank & Trust Co.
 5    Pennsylvania  27332    Fulton Bank, National Association
 6            Iowa   8758            Iowa Trust & Savings Bank
 7          Kansas  25851               Dream First Bank, N.A.
 8      California  59017            JPMorgan Chase Bank, N.A.
 9        New York  57053                  Flagstar Bank, N.A.
 10     California  24735  First–Citizens Bank & Trust Company
 11         Kansas  15426                          Equity Bank
 12        Florida  16748            United Fidelity Bank, fsb
 13  West Virginia  14361                       MVB Bank, Inc.
 14       Nebraska  18265           Farmers and Merchants Bank
 15     New Jersey  21111                      Industrial Bank
 16           Ohio  58317                   Buckeye State Bank
 17       Kentucky  58112    Kentucky Farmers Bank Corporation
 18          Texas  10716                   Legend Bank, N. A.
 19       Illinois  30570                   Royal Savings Bank
 20         Kansas  17719                          Conway Bank
 21       Illinois   1802            United Fidelity Bank, fsb
 22      Wisconsin  30003  First-Citizens Bank & Trust Company
 23      Louisiana  58302                         Whitney Bank
 24           Utah  35495                    Cache Valley Bank

          Closing Date  Fund  Sort ascending
 0         May 1, 2026                 10551
 1    January 30, 2026                 10550
 2       June 27, 2025                 10549
 3    January 17, 2025                 10548
 4    October 18, 2024                 10547
 5      April 26, 2024                 10546
 6    November 3, 2023                 10545
 7       July 28, 2023                 10544
 8         May 1, 2023                 10543
 9      March 12, 2023                 10540
 10     March 10, 2023                 10539
 11   October 23, 2020                 10538
 12   October 16, 2020                 10537
 13      April 3, 2020                 10536
 14  February 14, 2020                 10535
 15   November 1, 2019                 10534
 16   October 25, 2019                 10533
 17   October 25, 2019                 10532
 18       May 31, 2019                 10531
 19  December 15, 2017                 10530
 20   October 13, 2017                 10529
 21       May 26, 2017                 10528
 22        May 5, 2017                 10527
 23     April 28, 2017                 10526
 24      March 3, 2017                 10525  ]

In [18]:
df[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
1,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
2,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
3,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
4,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
5,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
6,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
7,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
8,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
9,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
10,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
11,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
12,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
13,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
14,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
15,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
16,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
17,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
18,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
19,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
20,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
21,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
22,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
23,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526
24,Proficio Bank,Cottonwood Heights,Utah,35495,Cache Valley Bank,"March 3, 2017",10525

READING DATA FROM WIKIPEDIA(HTML) USING PANDAS

In [25]:
!pip install requests

Collecting requests
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting charset_normalizer<4,>=2 (from requests)
  Downloading charset_normalizer-3.4.7-cp310-cp310-win_amd64.whl.metadata (41 kB)
Collecting idna<4,>=2.5 (from requests)
  Downloading idna-3.17-py3-none-any.whl.metadata (6.4 kB)
Collecting urllib3<3,>=1.26 (from requests)
  Downloading urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2023.5.7 (from requests)
  Downloading certifi-2026.5.20-py3-none-any.whl.metadata (2.5 kB)
Downloading requests-2.34.2-py3-none-any.whl (73 kB)
Downloading charset_normalizer-3.4.7-cp310-cp310-win_amd64.whl (159 kB)
Downloading idna-3.17-py3-none-any.whl (65 kB)
Downloading urllib3-2.7.0-py3-none-any.whl (131 kB)
Downloading certifi-2026.5.20-py3-none-any.whl (134 kB)
Installing collected packages: urllib3, idna, charset_normalizer, certifi, requests

   ---------------------------------------- 0/5 [urllib3]
   -------- ------------------------------- 1/5 [idna]
   ---------------- ----------------------- 2/5 [charset_normalizer]
   -------------------------------- ------- 4/5 [requests]
   ---------------------------------------- 5/5 [requests]

Successfully installed certifi-2026.5.20 charset_normalizer-3.4.7 idna-3.17 requests-2.34.2 urllib3-2.7.0

HERE WE INSTALL REQUESTS BECAUSE 
Very Simple Understanding

When you open a website in Chrome:

Browser → sends request → Website server

The server then sends back:

HTML
JSON
images
data

requests lets Python behave like a browser.

In [26]:
import pandas as pd
import requests

url = "https://en.wikipedia.org/wiki/Mobile_country_code"

headers = {
    "User-Agent":"Mozilla/5.0"
}

response = requests.get(url, headers=headers)

df = pd.read_html(response.text, match="Country", header=0)

print(df[0])

     Mobile country code                                    Country ISO 3166  \
0                    289                                 A Abkhazia    GE-AB
1                    412                                Afghanistan       AF
2                    276                                    Albania       AL
3                    603                                    Algeria       DZ
4                    544  American Samoa (United States of America)       AS
..                   ...                                        ...      ...
247                  452                                    Vietnam       VN
248                  543                        W Wallis and Futuna       WF
249                  421                                    Y Yemen       YE
250                  645                                   Z Zambia       ZM
251                  648                                   Zimbabwe       ZW

                                  Mobile network codes National MNC authority  \
0             List of mobile network codes in Abkhazia                    NaN
1          List of mobile network codes in Afghanistan                    NaN
2              List of mobile network codes in Albania                    NaN
3              List of mobile network codes in Algeria                    NaN
4       List of mobile network codes in American Samoa                    NaN
..                                                 ...                    ...
247        List of mobile network codes in the Vietnam                    NaN
248  List of mobile network codes in Wallis and Futuna                    NaN
249          List of mobile network codes in the Yemen                    NaN
250             List of mobile network codes in Zambia                    NaN
251           List of mobile network codes in Zimbabwe                    NaN

                      Remarks
0    MCC is not listed by ITU
1                         NaN
2                         NaN
3                         NaN
4                         NaN
..                        ...
247                       NaN
248                       NaN
249                       NaN
250                       NaN
251                       NaN

[252 rows x 6 columns]

C:\Users\Soham Khade\AppData\Local\Temp\ipykernel_19320\522809670.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(response.text, match="Country", header=0)

In [27]:
df[0]

,Mobile country code,Country,ISO 3166,Mobile network codes,National MNC authority,Remarks
0,289,A Abkhazia,GE-AB,List of mobile network codes in Abkhazia,NaN,MCC is not listed by ITU
1,412,Afghanistan,AF,List of mobile network codes in Afghanistan,NaN,NaN
2,276,Albania,AL,List of mobile network codes in Albania,NaN,NaN
3,603,Algeria,DZ,List of mobile network codes in Algeria,NaN,NaN
4,544,American Samoa (United States of America),AS,List of mobile network codes in American Samoa,NaN,NaN
...,...,...,...,...,...,...
247,452,Vietnam,VN,List of mobile network codes in the Vietnam,NaN,NaN
248,543,W Wallis and Futuna,WF,List of mobile network codes in Wallis and Futuna,NaN,NaN
249,421,Y Yemen,YE,List of mobile network codes in the Yemen,NaN,NaN
250,645,Z Zambia,ZM,List of mobile network codes in Zambia,NaN,NaN
251,648,Zimbabwe,ZW,List of mobile network codes in Zimbabwe,NaN,NaN

READING A EXCEL FILE USING PANDAS

In [35]:
!pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [36]:
df=pd.read_excel("study.xlsx")

In [37]:
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,2. Weekly Breakdown and Subject Allocation,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,Week,Day,Session 1 (9:00 - 11:00 AM),Session 2 (1:00 - 3:00 PM),Session 3 (5:00 - 7:00 PM),Focus Areas
2,NaN,NaN,NaN,NaN,Nov 4 - Nov 10,Monday,Discrete Mathematics,OOP,Fundamentals of Data Structures,"Discrete Math (Set theory), OOP (Classes, obje..."
3,NaN,NaN,NaN,NaN,NaN,Tuesday,Computer Graphics,Digital Electronics,Discrete Mathematics,"Computer Graphics (Basics), DELD (Logic gates)..."
4,NaN,NaN,NaN,NaN,NaN,Wednesday,Fundamentals of Data Structures,OOP,Computer Graphics,"Data Structures (Linked lists), OOP (Encapsula..."
5,NaN,NaN,NaN,NaN,NaN,Thursday,Discrete Mathematics,Digital Electronics,Fundamentals of Data Structures,"Discrete Math (Proofs), DELD (Circuits), Data ..."
6,NaN,NaN,NaN,NaN,NaN,Friday,Computer Graphics,OOP,Digital Electronics,"CG (Transformations), OOP (Inheritance), DELD ..."
7,NaN,NaN,NaN,NaN,NaN,Saturday,Discrete Mathematics,Digital Electronics,Fundamentals of Data Structures,"Discrete Math (Advanced Combinatorics), DELD (..."
8,NaN,NaN,NaN,NaN,Nov 11 - Nov 15,Monday,Computer Graphics,OOP,Discrete Mathematics,Review core concepts and practice problems in ...
9,NaN,NaN,NaN,NaN,NaN,Tuesday,Fundamentals of Data Structures,Digital Electronics,Computer Graphics,"Data structure applications, DELD (Timing diag..."
10,NaN,NaN,NaN,NaN,NaN,Wednesday,Discrete Mathematics,OOP,Fundamentals of Data Structures,Mock tests on foundational concepts
11,NaN,NaN,NaN,NaN,NaN,Thursday,Computer Graphics,Digital Electronics,Discrete Mathematics,Advanced problem-solving and complex concepts
12,NaN,NaN,NaN,NaN,NaN,Friday,Fundamentals of Data Structures,OOP,Computer Graphics,"Begin practicing past papers for FDS and OOP, ..."
13,NaN,NaN,NaN,NaN,Nov 16 - Nov 24,Monday,Discrete Mathematics,Digital Electronics,Fundamentals of Data Structures,Practice mock exams on all core topics
14,NaN,NaN,NaN,NaN,NaN,Tuesday,Computer Graphics,OOP,Discrete Mathematics,Mock tests with timing practice
15,NaN,NaN,NaN,NaN,NaN,Wednesday,Fundamentals of Data Structures,Digital Electronics,Computer Graphics,Targeted review of weak areas in FDS and CG
16,NaN,NaN,NaN,NaN,NaN,Thursday,Discrete Mathematics,OOP,Fundamentals of Data Structures,Final adjustments based on mock test results
17,NaN,NaN,NaN,NaN,NaN,Friday,Computer Graphics,Digital Electronics,Discrete Mathematics,"Full past papers for each subject, focus on re..."
18,NaN,NaN,NaN,NaN,NaN,Saturday,Fundamentals of Data Structures,OOP,Computer Graphics,Targeted revision for upcoming exams
19,NaN,NaN,NaN,NaN,NaN,Sunday,Rest and Light Revision,Rest and Light Revision,Rest and Light Revision,Rest day for mental refreshment

READING A PICKLE FILE USING PANDAS

What is a Pickle File in Python?

A Pickle file is a file used to:

Store Python objects permanently,so that they can be used next time directly  

Python converts objects into binary format and saves them.

In [ ]:
df.to_pickle('df')#converted excel file into pickle file

In [41]:
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,2. Weekly Breakdown and Subject Allocation,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,Week,Day,Session 1 (9:00 - 11:00 AM),Session 2 (1:00 - 3:00 PM),Session 3 (5:00 - 7:00 PM),Focus Areas
2,NaN,NaN,NaN,NaN,Nov 4 - Nov 10,Monday,Discrete Mathematics,OOP,Fundamentals of Data Structures,"Discrete Math (Set theory), OOP (Classes, obje..."
3,NaN,NaN,NaN,NaN,NaN,Tuesday,Computer Graphics,Digital Electronics,Discrete Mathematics,"Computer Graphics (Basics), DELD (Logic gates)..."
4,NaN,NaN,NaN,NaN,NaN,Wednesday,Fundamentals of Data Structures,OOP,Computer Graphics,"Data Structures (Linked lists), OOP (Encapsula..."
5,NaN,NaN,NaN,NaN,NaN,Thursday,Discrete Mathematics,Digital Electronics,Fundamentals of Data Structures,"Discrete Math (Proofs), DELD (Circuits), Data ..."
6,NaN,NaN,NaN,NaN,NaN,Friday,Computer Graphics,OOP,Digital Electronics,"CG (Transformations), OOP (Inheritance), DELD ..."
7,NaN,NaN,NaN,NaN,NaN,Saturday,Discrete Mathematics,Digital Electronics,Fundamentals of Data Structures,"Discrete Math (Advanced Combinatorics), DELD (..."
8,NaN,NaN,NaN,NaN,Nov 11 - Nov 15,Monday,Computer Graphics,OOP,Discrete Mathematics,Review core concepts and practice problems in ...
9,NaN,NaN,NaN,NaN,NaN,Tuesday,Fundamentals of Data Structures,Digital Electronics,Computer Graphics,"Data structure applications, DELD (Timing diag..."
10,NaN,NaN,NaN,NaN,NaN,Wednesday,Discrete Mathematics,OOP,Fundamentals of Data Structures,Mock tests on foundational concepts
11,NaN,NaN,NaN,NaN,NaN,Thursday,Computer Graphics,Digital Electronics,Discrete Mathematics,Advanced problem-solving and complex concepts
12,NaN,NaN,NaN,NaN,NaN,Friday,Fundamentals of Data Structures,OOP,Computer Graphics,"Begin practicing past papers for FDS and OOP, ..."
13,NaN,NaN,NaN,NaN,Nov 16 - Nov 24,Monday,Discrete Mathematics,Digital Electronics,Fundamentals of Data Structures,Practice mock exams on all core topics
14,NaN,NaN,NaN,NaN,NaN,Tuesday,Computer Graphics,OOP,Discrete Mathematics,Mock tests with timing practice
15,NaN,NaN,NaN,NaN,NaN,Wednesday,Fundamentals of Data Structures,Digital Electronics,Computer Graphics,Targeted review of weak areas in FDS and CG
16,NaN,NaN,NaN,NaN,NaN,Thursday,Discrete Mathematics,OOP,Fundamentals of Data Structures,Final adjustments based on mock test results
17,NaN,NaN,NaN,NaN,NaN,Friday,Computer Graphics,Digital Electronics,Discrete Mathematics,"Full past papers for each subject, focus on re..."
18,NaN,NaN,NaN,NaN,NaN,Saturday,Fundamentals of Data Structures,OOP,Computer Graphics,Targeted revision for upcoming exams
19,NaN,NaN,NaN,NaN,NaN,Sunday,Rest and Light Revision,Rest and Light Revision,Rest and Light Revision,Rest day for mental refreshment

In [42]:
pd.read_pickle('df')

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,2. Weekly Breakdown and Subject Allocation,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,Week,Day,Session 1 (9:00 - 11:00 AM),Session 2 (1:00 - 3:00 PM),Session 3 (5:00 - 7:00 PM),Focus Areas
2,NaN,NaN,NaN,NaN,Nov 4 - Nov 10,Monday,Discrete Mathematics,OOP,Fundamentals of Data Structures,"Discrete Math (Set theory), OOP (Classes, obje..."
3,NaN,NaN,NaN,NaN,NaN,Tuesday,Computer Graphics,Digital Electronics,Discrete Mathematics,"Computer Graphics (Basics), DELD (Logic gates)..."
4,NaN,NaN,NaN,NaN,NaN,Wednesday,Fundamentals of Data Structures,OOP,Computer Graphics,"Data Structures (Linked lists), OOP (Encapsula..."
5,NaN,NaN,NaN,NaN,NaN,Thursday,Discrete Mathematics,Digital Electronics,Fundamentals of Data Structures,"Discrete Math (Proofs), DELD (Circuits), Data ..."
6,NaN,NaN,NaN,NaN,NaN,Friday,Computer Graphics,OOP,Digital Electronics,"CG (Transformations), OOP (Inheritance), DELD ..."
7,NaN,NaN,NaN,NaN,NaN,Saturday,Discrete Mathematics,Digital Electronics,Fundamentals of Data Structures,"Discrete Math (Advanced Combinatorics), DELD (..."
8,NaN,NaN,NaN,NaN,Nov 11 - Nov 15,Monday,Computer Graphics,OOP,Discrete Mathematics,Review core concepts and practice problems in ...
9,NaN,NaN,NaN,NaN,NaN,Tuesday,Fundamentals of Data Structures,Digital Electronics,Computer Graphics,"Data structure applications, DELD (Timing diag..."
10,NaN,NaN,NaN,NaN,NaN,Wednesday,Discrete Mathematics,OOP,Fundamentals of Data Structures,Mock tests on foundational concepts
11,NaN,NaN,NaN,NaN,NaN,Thursday,Computer Graphics,Digital Electronics,Discrete Mathematics,Advanced problem-solving and complex concepts
12,NaN,NaN,NaN,NaN,NaN,Friday,Fundamentals of Data Structures,OOP,Computer Graphics,"Begin practicing past papers for FDS and OOP, ..."
13,NaN,NaN,NaN,NaN,Nov 16 - Nov 24,Monday,Discrete Mathematics,Digital Electronics,Fundamentals of Data Structures,Practice mock exams on all core topics
14,NaN,NaN,NaN,NaN,NaN,Tuesday,Computer Graphics,OOP,Discrete Mathematics,Mock tests with timing practice
15,NaN,NaN,NaN,NaN,NaN,Wednesday,Fundamentals of Data Structures,Digital Electronics,Computer Graphics,Targeted review of weak areas in FDS and CG
16,NaN,NaN,NaN,NaN,NaN,Thursday,Discrete Mathematics,OOP,Fundamentals of Data Structures,Final adjustments based on mock test results
17,NaN,NaN,NaN,NaN,NaN,Friday,Computer Graphics,Digital Electronics,Discrete Mathematics,"Full past papers for each subject, focus on re..."
18,NaN,NaN,NaN,NaN,NaN,Saturday,Fundamentals of Data Structures,OOP,Computer Graphics,Targeted revision for upcoming exams
19,NaN,NaN,NaN,NaN,NaN,Sunday,Rest and Light Revision,Rest and Light Revision,Rest and Light Revision,Rest day for mental refreshment